name: "Test Push Trigger"
on:
  push:
    branches:
      - test/optimise_ci
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Print Branch
        run: echo "Triggered on branch: ${{ github.ref }}"
